export const list = [
  {
    id: 1,
    title: 'Căn hộ 1',
    bedAmount: 3,
    bathAmount: 2,
    carAmount: 1,
    imgSrc: require('../../assets/images/thumb-small1.png'),
    status: 'available',
  },
  {
    id: 2,
    title: 'Căn hộ 2',
    bedAmount: 3,
    bathAmount: 2,
    carAmount: 1,
    imgSrc: require('../../assets/images/thumb-small2.png'),
    status: 'hired',
  },
  {
    id: 3,
    title: 'Căn hộ 3',
    bedAmount: 3,
    bathAmount: 2,
    carAmount: 1,
    imgSrc: require('../../assets/images/thumb-small3.png'),
    status: 'available',
  },
  {
    id: 4,
    title: 'Căn hộ 4',
    bedAmount: 3,
    bathAmount: 2,
    carAmount: 1,
    imgSrc: require('../../assets/images/thumb-small4.png'),
    status: 'hired',
  },
  {
    id: 5,
    title: 'Căn hộ 5',
    bedAmount: 3,
    bathAmount: 2,
    carAmount: 1,
    imgSrc: require('../../assets/images/thumb-small1.png'),
    status: 'available',
  },
  {
    id: 6,
    title: 'Căn hộ 6',
    bedAmount: 3,
    bathAmount: 2,
    carAmount: 1,
    imgSrc: require('../../assets/images/thumb-small2.png'),
    status: 'hired',
  },
  {
    id: 7,
    title: 'Căn hộ 7',
    bedAmount: 3,
    bathAmount: 2,
    carAmount: 1,
    imgSrc: require('../../assets/images/thumb-small3.png'),
    status: 'available',
  },
  {
    id: 8,
    title: 'Căn hộ 8',
    bedAmount: 3,
    bathAmount: 2,
    carAmount: 1,
    imgSrc: require('../../assets/images/thumb-small4.png'),
    status: 'hired',
  },
];
